version: '3.4'

networks:
  backend:
    driver: bridge

services:

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:80
    volumes:
      - portainer_data:/portainer_data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - backend
    environment:
      - VIRTUAL_HOST=langaracs.tech
      - VIRTUAL_PATH=/portainer
      - LETSENCRYPT_HOST=langaracs.tech
      - LETSENCRYPT_EMAIL=langaracompsciclub@gmail.com

  # watchtower - keeps other containers updated
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    ports:
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    environment:
      # set timezone
      - TZ=America/Vancouver 
      # delete old containers
      - WATCHTOWER_CLEANUP=true
      # revive containers with updates
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      # post updates to logging channel
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_LOG_CHANNEL}
      
      # Use HTTP request to check for an image update
      # curl -H "Authorization: Bearer token" localhost:8080/v1/update
      - WATCHTOWER_HTTP_API_UPDATE=true
      # Set token for HTTP request from .env
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      # Also continue checking for updates automatically (every hour)
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true

      # nginx values
      - VIRTUAL_HOST=langaracs.tech
      - VIRTUAL_PATH=/watchtower
      - LETSENCRYPT_HOST=langaracs.tech
      - LETSENCRYPT_EMAIL=langaracompsciclub@gmail.com


  # runs our discord bot peregrine
  peregrine:
    container_name: peregrine
    image: "ghcr.io/langaracpsc/peregrine:latest"
    networks:
      - backend
    environment:
      - DISCORD_BOT_TOKEN
      - WATCHTOWER_HTTP_API_TOKEN

  # Website
  langaracpsc-next:
    container_name: website
    ports:
      - '3000:3000'
    image: "ghcr.io/langaracpsc/langaracpsc-next:latest"
    networks:
      - backend
    environment:
      - VIRTUAL_HOST=langaracs.tech
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=langaracs.tech
      - LETSENCRYPT_EMAIL=langaracompsciclub@gmail.com

  # LCSC Website API
  langaracpsc.webapi:
    container_name: webapi
    image: "ghcr.io/langaracpsc/langaracpsc.webapi:latest"
    depends_on:
      - "postgres_image"
    ports:
      - "8000:80"     
    networks:
      - backend
    environment:     
      - HOSTNAME=${PG_HOSTNAME}
      - DATABASE=${PG_DATABASE}
      - USERNAME=${PG_USERNAME}
      - PASSWORD=${PG_PASSWORD}
      - PORT=${PG_PORT} 

      - VIRTUAL_HOST=api.langaracs.tech
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=api.langaracs.tech
      - LETSENCRYPT_EMAIL=langaracompsciclub@gmail.com

  # Postgres database for langaracpsc.webapi
  postgres_image:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - backend
    volumes:
      - ./data/db:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USERNAME}

  # Langara Course API from Anderson
  langara-api:
    container_name: langaraapi
    ports:
      - '5000:5000'
    image: "ghcr.io/highfire1/langara-course-api:latest"
    networks:
      - backend
    environment:
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      
      - VIRTUAL_HOST=api2.langaracs.tech
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=api2.langaracs.tech
      - LETSENCRYPT_EMAIL=langaracompsciclub@gmail.com
      

  # Nginx
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
    networks:
      - backend
    network_mode: bridge

  # Generates reverse proxy templates of each service for nginx
  docker-gen:
    container_name: docker-gen
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx-proxy -watch /etc/docker-proxy-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes_from:
      - nginx-proxy
    volumes:
      - ./nginx/nginx.tmpl:/etc/docker-proxy-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    networks:
      - backend

  # creates Let's Encrypt certificates
  acme-companion:
    container_name: nginx-proxy-acme
    image: nginxproxy/acme-companion

    environment:
      - DEFAULT_EMAIL=langaracompsciclub@gmail.com
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend

volumes:
  portainer_data:
  conf:
  vhost:
  html:
  certs:
  acme:
