version: "1.1"
services:

  # watchtower - keeps other containers updated
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      # set timezone
      - TZ=America/Vancouver 
      # delete old containers
      - WATCHTOWER_CLEANUP=true
      # post updates to logging channel
      # - WATCHTOWER_NOTIFICATION_URL=discord://8l1oQjhN8I01iRl_2HrjyCoRskHabxnlb-0JNUkwvyNSVQq1mg_XUHv3dvI48RKmKU5d@1089524517916901516
      
      # Use HTTP request to check for an image update
      # curl -H "Authorization: Bearer TOKEN" localhost:8080/v1/update
      - WATCHTOWER_HTTP_API_UPDATE=true
      # Set token for HTTP request from .env
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_TOKEN}
      # Also continue checking for updates automatically (default is daily)
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true

    # port for http request  
    ports:
      - 8080:8080


  # runs our discord bot peregrine
  discord:
    image: "ghcr.io/langaracpsc/peregrine:main"
    environment:
      - DISCORD_TOKEN
      - WATCHTOWER_TOKEN