version: "3.9"
services:

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/portainer_data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  # watchtower - keeps other containers updated
  watchtower:
    ports:
      - '8080:8080'
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # set timezone
      - TZ=America/Vancouver 
      # delete old containers
      - WATCHTOWER_CLEANUP=true
      # revive containers with updates
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      # post updates to logging channel
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_LOG_CHANNEL}
      
      # Use HTTP request to check for an image update
      # curl -H "Authorization: Bearer token" localhost:8080/v1/update
      - WATCHTOWER_HTTP_API_UPDATE=true
      # Set token for HTTP request from .env
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      # Also continue checking for updates automatically (every hour)
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true

  # runs our discord bot peregrine
  discord:
    network_mode: host 
    image: "ghcr.io/langaracpsc/peregrine:latest"
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN
      - WATCHTOWER_HTTP_API_TOKEN
     
  api:
    ports:
        - '5000:5000'
    image: "ghcr.io/highfire1/langara-course-api:latest"
    restart: unless-stopped

volumes:
    portainer_data: