version: "3.9"
services:

  # watchtower - keeps other containers updated
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # set timezone
      - TZ=America/Vancouver 
      # delete old containers
      - WATCHTOWER_CLEANUP=true
      # revive containers with updates
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true
      # post updates to logging channel
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_LOG_CHANNEL}
      
      # Use HTTP request to check for an image update
      # curl -H "Authorization: Bearer token" localhost:8080/v1/update
      - WATCHTOWER_HTTP_API_UPDATE=true
      # Set token for HTTP request from .env
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      # Also continue checking for updates automatically (every hour)
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true

    # port for http request  
    ports:
      - 8080:8080


  # runs our discord bot peregrine
  discord:
    image: "ghcr.io/langaracpsc/peregrine:latest"
    environment:
      - DISCORD_BOT_TOKEN
      - WATCHTOWER_HTTP_API_TOKEN
    # connect to watchtower container to send restart command
    links: 
     - watchtower
     
   api:
    image: "ghcr.io/highfire1/langara-course-api:latest"
    ports:
      - "5000:5000"
