version: '3.4'

services:

  # Peregrine, our discord bot
  peregrine:
    container_name: peregrine
    image: "ghcr.io/langaracpsc/peregrine:latest"
    networks:
      - backend
    environment:
      - DISCORD_BOT_TOKEN
      - WATCHTOWER_HTTP_API_TOKEN



  # Website
  langaracpsc-next:
    container_name: website
    ports:
      - '3000:3000'
    image: "ghcr.io/langaracpsc/langaracpsc-next:latest"
    networks:
      - backend
   

  # Website API
  langaracpsc.webapi:
    container_name: webapi
    image: "ghcr.io/langaracpsc/langaracpsc.webapi:latest"
    depends_on:
      - "postgres_image"
    ports:
      - "8000:80"
    networks:
      - backend
    environment:
      - HOSTNAME=${PG_HOSTNAME}
      - DATABASE=${PG_DATABASE}
      - USERNAME=${PG_USERNAME}
      - PASSWORD=${PG_PASSWORD}
      - PORT=${PG_PORT}

  # Postgres database that backs langaracpsc.webapi
  postgres_image:
    container_name: postgres
    image: postgres:latest
    restart: always
    networks:
      - backend
    volumes:
      - postgres_db:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USERNAME}


  # Langara Course API
  langara-api:
    container_name: langaraapi
    ports:
      - '5000:5000'
    image: "ghcr.io/langaracpsc/langaracoursewatcher:latest"
    networks:
      - backend
    volumes:
      - course_watcher_db:/database
    environment:
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}


  # Langara Course Planner
  langara-course-planner:
    container_name: langara-course-planner
    ports:
      - '5001:80'
    image: 'ghcr.io/langaracpsc/langaracourseplanner:latest'


  # === SYSADMIN TOOLS === #


  # NGINX manager
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginxpm_data:/data
      - nginxpm_letsencrypt:/etc/letsencrypt
    networks:
      - backend



  # Portainer, docker container manager
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped



  # Watchtower keeps images up to date
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    ports:
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend
    environment:
      # set timezone
      - TZ=America/Vancouver 
      # delete old containers
      - WATCHTOWER_CLEANUP=true
      # revive containers with updates
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=true

      # post updates to logging channel
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_LOG_CHANNEL}
      # but not startup messages
      - WATCHTOWER_NO_STARTUP_MESSAGE=true

      # Use HTTP request to check for an image update
      # curl -H "Authorization: Bearer token" localhost:8080/v1/update
      - WATCHTOWER_HTTP_API_UPDATE=true
      # Set token for HTTP request from .env
      - WATCHTOWER_HTTP_API_TOKEN=${WATCHTOWER_HTTP_API_TOKEN}
      # Also continue checking for updates automatically (every hour)
      - WATCHTOWER_POLL_INTERVAL=3600
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true


networks:
  backend:
    driver: bridge


volumes:
  postgres_db:

  course_watcher_db:

  portainer_data:

  nginxpm_data:
  nginxpm_letsencrypt:
